# Generated by Django 4.2 on 2023-11-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_alter_product_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=100, verbose_name='Тип доставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки, руб.')),
                ('duration', models.CharField(max_length=100, verbose_name='Срок доставки')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='Номер отслеживания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
