# Generated by Django 4.2 on 2023-11-23 18:08

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_status_alter_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=16, max_length=40, prefix=''),
        ),
    ]
