# Generated by Django 4.2 on 2023-11-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_pro_id_1472ef_idx',
            old_fields=('id', 'sku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Артикуль'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_pro_name_b60cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-date'], name='product_pro_date_256c6f_idx'),
        ),
    ]
