# Generated by Django 4.2 on 2023-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_id_sku_product_pro_id_1472ef_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_id_1472ef_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='slug',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='product_pro_id_b9e5a0_idx'),
        ),
    ]
