# Generated by Django 4.2 on 2023-11-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_model',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
